# -*- coding: utf-8 -*-
"""Flask Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-H3xXLHgzgmJJJdmzPOtP_lbSRI9TD5A
"""

#Question-1. What is RESTful API?
''' Restful API is an interfce that allows different application with each other
    over the internet using HTTP method like GET,POST,PUT, and DELETE.'''

#Question-2. What is Flask, and why is it popular for building APIs?
''' Flask is a lightweight web framework in Python used to build web applications
and APIs.
Flask is populer for bulding API. It has minimal setup and is easy for beginners.
Developers can add only the libraries they need.Creating API endpoints is very
simple.

#Question-3. What are HTTP methods used in RESTful APIs?
''' HTTP methods is used for different operations in RESTfuls APIs.
For example-
GET- This is used for Data retrieve from Server.
POST- Used for create new data in the Server.
PUT- Used for completely update to existing data.
Delete- Used for data deleting from Server.

#Question-4. What is the purpose of the @app.route() decorator in Flask?
''' In Flask, the @app.route() decorator is used to map a URL to a specific
Python function, so when a user visits that URL, the function runs and returns
a response.

#Question-5. What is the role of Flask-SQL Alchemy?
''' It connects a flask application to database like MySQL, SQLite,or PostgreSQL.
It allows us to represent database tables as Python classes and rows as objects.

#Question-7. How do you return JSON responses?
''' In Flask, We can return JSON responses using the jsonify() function.
Jsonify() converts a Python dictionary into JSON formate.
JSON response is automatically sent to the client with the correct HTTP headers.'''

#Question-8. How do you handle POST requests in flask?
''' In Flask, a POST request is handled by specifying the POST method in
@app.route() and using request to get the data sent by the client.

#Question-9. How do you handle errors in flask.
''' In Flask, errors are handled using error handlers with the @app.errorhandler()
decorator.'''